name: "Bug报告"
description: "SpeeKlik本身造成的Bug可以在这里报告"
labels: [New Report, Bug]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "检查是否是SpeeKlik的错误，而非其他原因。"
    options:
    - label: "我使用了正常发行的SpeeKlik，但仍出现错误"
      required: true
    - label: "我在Issues中搜索并确认了没有重复其他Issue"
      required: true
    - label: "我发誓没有胡乱操作一通导致SpeeKlik懵逼然后造成错误"
      required: false
- type: textarea
  id: "yml-2"
  attributes:
    label: 原因
    description: "你到底做了啥子导致错误发生"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 现象
    description: "SpeeKlik到底发了什么疯"
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: 环境
    description: "你的电脑的彻底情况（如Windows11专业工作站版24H2）"
  validations:
    required: false
- type: textarea
  id: "yml-5"
  attributes:
    label: 附件
    description: "你有什么视频/图片/Log来帮助Debug，尽管交出来吧"
    placeholder: "点进这里，然后把文件喂给GitHub"
  validations:
    required: false